version: '3.9'

services:

  # PostgreSQL database
  db:
    image: postgres:15
    container_name: defence_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: defence_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - defence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d defence_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  fastapi:
    build: ./fastapi_app
    container_name: defence_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:admin@db:5432/defence_db
      PYTHONPATH: /app:/workspace
      FASTAPI_PUBLIC_URL: http://localhost:8000
    volumes:
      - ./fastapi_app:/app
      - ./database:/workspace/database
      - ./model:/workspace/model
      - ./Data:/opt/airflow/Data
    working_dir: /app
    command: ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - defence_network

  webapp:
    build: ./webapp
    container_name: defence_streamlit
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    environment:
      FASTAPI_URL: http://fastapi:8000
    volumes:
      - ./webapp:/app
    command: ["streamlit", "run", "main.py", "--server.address=0.0.0.0"]
    networks:
      - defence_network

  airflow:
    build: ./airflow
    container_name: defence_airflow
    depends_on:
      db:
        condition: service_healthy
      fastapi:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@db:5432/defence_db

      RAW_DATA_DIR: /opt/airflow/Data/raw
      GOOD_DATA_DIR: /opt/airflow/Data/good_data
      FASTAPI_URL: http://fastapi:8000/predict
      DATABASE_URL: postgresql+psycopg2://admin:admin@db:5432/defence_db

      FASTAPI_PUBLIC_URL: http://localhost:8000
      TEAMS_WEBHOOK: ${TEAMS_WEBHOOK}

      PYTHONPATH: /opt/airflow:/opt/airflow/dags:/opt/airflow/database
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./Data:/opt/airflow/Data
      - ./database:/opt/airflow/database
    ports:
      - "8080:8080"
    command: ["bash", "-c",
      "airflow db init &&
       airflow users create --username admin --password admin --role Admin --firstname Max --lastname Fry --email admin@example.com || true &&
       airflow webserver & airflow scheduler"
    ]
    networks:
      - defence_network

  grafana:
    image: grafana/grafana:latest
    container_name: defence_grafana
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:

      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel


      - GF_SERVER_ROOT_URL=http://localhost:3000


      - GF_LOG_LEVEL=info
    volumes:

      - grafana_data:/var/lib/grafana


      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - defence_network
    restart: unless-stopped


networks:
  defence_network:
    driver: bridge
    name: defence_network

volumes:
  db_data:
  grafana_data: