#version: "3.9"

services:
  db:
    image: postgres:15
    container_name: defence_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: defence_db
    volumes:
      - db_data:/var/lib/postgresql/data
    command: >
      bash -c "
      docker-entrypoint.sh postgres &
      sleep 5 &&
      PGPASSWORD=admin psql -U admin -d defence_db -c 'CREATE DATABASE airflow_db;' || true &&
      wait
      "

  airflow:
    build: ./airflow
    container_name: defence_airflow
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@db:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/config:/opt/airflow/config
      - ./airflow/great_expectations:/opt/airflow/great_expectations
    command: ["airflow", "standalone"]

  fastapi:
    build: ./fastapi_app
    container_name: defence_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/defence_db
      - PYTHONPATH=/app:/workspace
    volumes:
      - ./fastapi_app:/app
      - ./database:/workspace/database
      - ./model:/workspace/model
    working_dir: /app
    command: ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  webapp:
    build: ./webapp
    container_name: defence_streamlit
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://fastapi:8000
    volumes:
      - ./webapp:/app
    command: ["streamlit", "run", "main.py", "--server.address=0.0.0.0"]

volumes:
  db_data: