#apiVersion: 1
#
#datasources:
#  - name: defence_db
#    type: postgres
#    access: proxy
#    url: defence_db:5432
#    database: defence_db
#    user: admin
#    secureJsonData:
#      password: admin
#    jsonData:
#      sslmode: disable
#      postgresVersion: 1300
#    isDefault: true


apiVersion: 1

datasources:
  - name: defence_db
    type: postgres
    access: proxy
    url: db:5432
    database: defence_db
    user: admin
    secureJsonData:
      password: 'admin'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: true
    version: 1
    editable: true